name: Nodejs Server
version: "1.07"
slug: nodejs_for_ha
description: "A TCP server that integrates with Home Assistant"
url: "https://github.com/zakery292/homeassistant_nodjs"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386 
boot: auto
host_network: true
ports:
  "3000/tcp": 3000
ingress: true
ingress_port: 3000
options:
  dongleIP: null
  homeAssistantIP: null
  sendToLUX: false
  sendToHomeAssistant: false
schema:
  dongleIP: str
  homeAssistantIP: str
  sendToLUX: bool
  sendToHomeAssistant: bool
