name: Luxpower Dongle Server
version: "1.94"
slug: nodejs_for_ha
description: "Dongle Server to connect to BH/BG Dongles to enable access into HA Via Luxpython. This server will only work with extral equipment purchased seperatly"
url: "https://github.com/zakery292/homeassistant_nodjs"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386 
boot: auto
backup: cold
map: 
  - addon_config:rw
  
host_network: true
ports:
  "3000/tcp": 3000
  "4346/tcp": 4346
ingress: true
ingress_port: 3000
