name: Nodejs Server
version: "1.63"
slug: nodejs_for_ha
description: "A TCP server that integrates with Home Assistant"
url: "https://github.com/zakery292/homeassistant_nodjs"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386 
boot: auto
backup: cold
map: 
  - addon_config:rw
  
host_network: true
ports:
  "3000/tcp": 3000
  "4346/tcp": 4346
ingress: true
ingress_port: 3000
