name: Luxpower Dongle Server Dev
version: "2.34"
slug: luxpower_server_dev
description: "Dongle Server to connect to BH/BG Dongles to enable access into HA Via Luxpython. This server will only work with extral equipment purchased seperatly"
url: "https://github.com/zakery292/luxpower_server/tree/main/luxpower_server_DEV"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386 
boot: auto
backup: cold
map: 
  - addon_config:rw
  
host_network: true
ports:
  "3000/tcp": 3000
  "4346/tcp": 4346
ingress: true
ingress_port: 3000
panel_icon: mdi-solar-panel-large